[build]
publish = "www"
command = "npm run build"

[template.environment]
ADMIN_API_KEY = "replace me with your generated secret"
COOKIE_JWT_SECRET = "replace me with your generated secret"

[[edge_functions]]
path = "/*"
function = "auth"
excludedPath = [
  "/api/auth/*",
  "/uploads/avatar/*",
  "/api/admin/*",
  "/images/*",
  "/uploads/*",
  "/css/*",
  "/favicon*",
  "/service-worker*",
]

[[edge_functions]]
path = "/*"
function = "partial"
excludedPath = ["/api/*", "/images/*", "/uploads/*", "/css/*"]

[[edge_functions]]
path = "/*"
function = "feedback"
excludedPath = ["/api/*", "/images/*", "/uploads/*", "/css/*"]

[[edge_functions]]
path = "/"
function = "latest-posts"

[[redirects]]
from = "/images/avatar/small/:username"
to = "/.netlify/images?url=/uploads/avatar/:username&width=256&height=256&fit=cover"
status = 200

[[redirects]]
from = "/images/*"
to = "/.netlify/images?url=/images/:splat"
status = 200
